### ISSUE TITLE
Unknown Roles

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-labs#6]
Hey @depizol, @smartameer, @ankitstarski, @Anonymas, @kgenkov, ~~@zapashcanon~~, @matinhus, and @nikhiljohny!

You're being pinged because you're listed on the Numix Team page, but don't currently have a role asigned on [our spreadsheet](https://docs.google.com/spreadsheets/d/1172wcKvRNxwi_6QmRq_Z7SUXsB0Ys2tT6OW42yKeIBA). We're building up to a redesign of the website so that it reflects the current state of the project so need this information so we can add you.

We also need your Telegram account names so we can add you to the developer chat there (this applies to everyone except @depizol, @zapashcanon, and @nikhiljohny whose we already have).

Thanks,
Josh

**Comment by zapashcanon** [comment]
Hi,

I just answered to your mail.

I also wonder if there's any plan to use something like [this](https://github.com/FruitieX/teleirc) ? I some kinda never use Telegram... it would be great to have this kind of gateway. :)

**Comment by Foggalong** [comment]
@zapashcanon No plans as of yet no. I should note that the Telegram dev chat is private not public (not everything discussed there is ready for public release), so I don't know if teleirc would still play well with it?

**Comment by zapashcanon** [comment]
I have no idea... I never used teleirc, I just give it as an example, but I'm sure there's a way to do this with teleirc or another software. ;)

**Comment by Foggalong** [comment]
@zapashcanon I'm completely clueless about this kind of thing, but if you do find something and need my help setting it up then just give me a ping :)

**Comment by zapashcanon** [comment]
Ok, I'll try to have a look at it in a few weeks then. ;)
